### PR TITLE
Fix headings levels for accessibility.

### PR DESCRIPTION
**Pull request by DuaelFr**
For accessibility (and SEO), it's best to start your page with a `h1` tag then keep a logical structure of headings into the page. It allows screen readers users to properly understand and navigate the page structure.

Note: I can't make hugo work locally so I wasn't able to test locally before openning this merge request. I hope it's not breaking the design.

### CODE REVIEW

**Comment by DuaelFr** [comment]
Given the [live preview](https://deploy-preview-39--postmeritocracy.netlify.com/) (what a great tool you built!) it seems visually OK :)

**Comment by CoralineAda** [comment]
Can you please fix the merge conflict? Then I'm happy to merge!

**Comment by DuaelFr** [comment]
Job done!
The github UI to resolve conflicts is quite useful :)

**Comment by CoralineAda** [comment]
Thanks so much!

**Pull request merged**
